### ISSUE TITLE
Update the Beta 3 Icons

### ISSUE THREAD

**Issue by alexkaessner** [KevinGutowski/Big-Sur-Icons#1]
Some icons got updated with the latest beta 3. So far I've seen changes for:
- [ ] Audio MIDI Setup
- [ ] Screenshot
- [ ] Dictionary
- [ ] Mission Control
- [ ] Music
- [ ] Wireless Diagnostics

Btw, the _Image Capture_ icon is also missing.

**Comment by KevinGutowski** [comment]
Thanks! Somehow I missed this issue. I'll look into updating all the icons
